server:
  port: 4044

runs-locally: ${RUNS_LOCALLY:true}

env: ${test_environment:local}
TEST_URL: https://localhost:4044

case:
  orchestration:
    service:
      base:
        uri: '#{environment["TEST_URL"].replaceFirst("https://", "http://")}'
    prepopulate:
      uri: ${case.orchestration.service.base.uri}/getSolicitorAndFeeDetails
    documentgenerate:
      uri: ${case.orchestration.service.base.uri}/generate-save-draft-document

prl:
  system-update:
    username: ${SYSTEM_UPDATE_USER_USERNAME:xxxxxx}
    password: ${PRL_SYSTEM_UPDATE_PASSWORD:xxxxxx}
  document:
    generate:
      uri: http://prl-dgs-aat.service.core-compute-aat.internal/health/liveness

management:
  endpoint:
    health:
      show-details: "always"
  endpoints:
    web:
      base-path: /
      exposure:
        include: health, info, prometheus

  #If you use a database then uncomment below lines and update db properties accordingly
spring:
  config:
    import: "optional:configtree:/mnt/secrets/"
  application:
    name: Prl cos api

azure:
  application-insights:
    instrumentation-key: ${APP_INSIGHTS_INSTRUMENTATION_KEY:00000000-0000-0000-0000-000000000000}

logging:
  level:
    org.springframework.web: DEBUG
    uk.gov.hmcts.reform.prl: DEBUG
    au.com.dius.pact: DEBUG
  pattern:
    console: "%d{yyyy-MMM-dd HH:mm:ss.SSS} %-5level [%thread] %logger{15} - %msg%n"

pba:
  validation:
    service:
      api:
        baseurl: ${PRD_API_BASEURL:http://localhost:8892}

feature-toggle:
  toggle:
    example: ${FEATURE_EXAMPLE:false}

xui:
  url: ${XUI_URL:https://manage-case.aat.platform.hmcts.net/cases/case-details}

uk:
  gov:
    notify:
      api:
        key: ${UK_GOV_NOTIFY_API_KEY:xxxxxxx}
        baseUrl: https://api.notifications.service.gov.uk
      email:
        templates:
          english:
            SOLICITOR: a080f4ce-a07f-43ec-a3f0-f196d83f7730
            CASEWORKER: 8c1cd107-b76f-4e10-9c44-afb49415cda2
            EXAMPLE: 50c74207-a341-4cd2-a073-71b218ad135e
          welsh:
            EXAMPLE: 50c74207-a341-4cd2-a073-71b218ad135e
        application:
          email-id: ${SOUTHAMPTON_COURT_EMAIL_ADDRESS:}
          court-name: Court Name

notify:
  api-key: fake-key
  baseUrl: https://api.notifications.service.gov.uk

send-grid:
  api-key: ${SEND_GRID_API_KEY:xxxxxxxx}
  rpa:
    email:
      to: ${RPA_NOTIFY_TO_EMAIL:xxxxxxxx}
      from: ${RPA_NOTIFY_FROM_EMAIL:xxxxxxxx}

payments:
  api:
    url: ${PAY_URL:http://payment-api-demo.service.core-compute-aat.internal}
    callback-url: ${PAY_CALLBACK_URL:http://payment-api-demo.service.core-compute-demo.internal/service-request-update}
  authorised-services: ${PRL_S2S_AUTHORISED_SERVICES:payment_app}

fees-register:
  api:
    url: ${FEE_REGISTER_API_URL:http://fees-register-api-aat.service.core-compute-aat.internal}
  parameters:
    C100_SUBMISSION_FEE:
      channel: default
      event: miscellaneous
      jurisdiction1: family
      jurisdiction2: family court
      keyword: ChildArrangement
      service: private law

# NEW BELOW THIS LINE

idam:
  s2s-auth:
    url: http://rpe-service-auth-provider-aat.service.core-compute-aat.internal
    microservice: prl_cos_api
    totp-secret: ${IDAM_S2S_AUTH_TOTP_SECRET:xxxxxxx}
  api:
    url: https://idam-api.aat.platform.hmcts.net
  client:
    id: prl-cos-api
    baseUrl: https://idam-api.aat.platform.hmcts.net
    redirect_uri: https://manage-case.aat.platform.hmcts.net/oauth2/callback
    secret: ${IDAM_CLIENT_SECRET:xxxxxxx}
    clientId: xuiwebapp
    authorize:
      context-path: /oauth2/authorize
    token:
      context-path: /oauth2/token
  user:
    genericpassword: ${PRL_GENERIC_PASSWORD:xxxxxx}

core_case_data:
  api:
    url: http://localhost:4452

resources:
  images:
    baseUrl: 'https://raw.githubusercontent.com/hmcts/prl-cos-api/master/resources/'

send-letter:
  url: http://rpe-send-letter-service-aat.service.core-compute-aat.internal

case_document_am:
  url: http://ccd-case-document-am-api-aat.service.core-compute-aat.internal

prl-dgs-api:
  url: ${PRL_DGS_API_URL:http://prl-dgs-aat.service.core-compute-aat.internal}

courtfinder:
  api:
    url: http://fact-api-aat.service.core-compute-aat.internal/

rd_professional:
  api:
    url: ${PRD_API_BASEURL:http://rd-professional-api-aat.service.core-compute-aat.internal}

launchdarkly:
  sdk-key: ${LAUNCH_DARKLY_SDK_KEY:}

document:
  templates:
    c100:
      c100_final_template: C100-Final-Document.docx
      c100_final_filename: C100FinalDocument.pdf
      c100_draft_template: PRL-C100-Draft-Final.docx
      c100_draft_filename: Draft_C100_application.pdf
      c100_c8_template: PRL-C8-Final-Changes.docx
      c100_c8_filename: C8Document.pdf
      c100_c1a_template: PRL-C1A.docx
      c100_c1a_filename: C1A_Document.pdf
      c100_final_welsh_template: PRL-Final-C100-WelshLang.docx
      c100_final_welsh_filename: C100FinalDocumentWelsh.pdf
      c100_draft_welsh_template: PRL-Draft-C100-WelshLang.docx
      c100_draft_welsh_filename: Draft_C100_application_welsh.pdf
      c100_c8_welsh_template: PRL-C8-WelshLang.docx
      c100_c8_welsh_filename: C8Document_Welsh.pdf
      c100_c1a_welsh_template: PRL-C1A-WelshLang.docx
      c100_c1a_welsh_filename: C1A_Document_Welsh.pdf
    fl401:
      fl401_final_template: FL401-Final.docx
      fl401_final_filename: FL401FinalDocument.pdf
      fl401_draft_template: FL401-draft.docx
      fl401_draft_filename: Draft_DA_application
      fl401_c8_template: PRL-DA-C8.docx
      fl401_c8_filename: C8_Document.pdf
      fl401_final_welsh_template: FL401-Final-Welsh.docx
      fl401_final_welsh_filename: FL401FinalDocumentWelsh.pdf
      fl401_draft_welsh_template: FL401-draft-Welsh.docx
      fl401_draft_welsh_filename: Draft_DA_Welsh_application
      fl401_c8_welsh_template: FL401-c8-welsh.docx
      fl401_c8_welsh_filename: C8_Document_Welsh.pdf

southampton:
  court:
    email-address: ${SOUTHAMPTON_COURT_EMAIL_ADDRESS:}
