apiVersion: v2
appVersion: "1.0"
description: A Helm chart for prl-cos-api App
name: prl-cos
home: https://github.com/hmcts/prl-cos-api
version: 0.0.63
maintainers:
  - name: HMCTS Family Private Law team
dependencies:
  - name: java
    version: 5.2.0
    repository: 'https://hmctspublic.azurecr.io/helm/v1/repo/'
