apiVersion: v2
appVersion: "1.0"
description: A Helm chart for prl-cos-api App
name: prl-cos
home: https://github.com/hmcts/prl-cos-api
version: 0.0.68
maintainers:
  - name: HMCTS Family Private Law team
dependencies:
  - name: java
    version: 5.3.0
    repository: 'oci://hmctspublic.azurecr.io/helm'
